using System;

namespace Cathedral.Game;

/// <summary>
/// Contains information about a player action choice.
/// Holds both the action text and metadata like related skill.
/// </summary>
public class ActionInfo
{
    /// <summary>
    /// The action text as generated by the LLM (may include "try to " prefix)
    /// </summary>
    public string ActionText { get; set; } = "";
    
    /// <summary>
    /// The skill associated with this action (e.g., "stealth", "strength", "intelligence")
    /// </summary>
    public string RelatedSkill { get; set; } = "";
    
    /// <summary>
    /// Gets the display text for the action, with "try to " prefix removed if present
    /// </summary>
    public string GetDisplayText()
    {
        string text = ActionText;
        
        // Remove "try to " prefix if present (case-insensitive)
        if (text.StartsWith("try to ", StringComparison.OrdinalIgnoreCase))
        {
            text = text.Substring(7); // Remove "try to "
        }
        
        return text;
    }
    
    /// <summary>
    /// Gets the formatted display text with skill prefix
    /// Example: "[stealth] infiltrate the castle at night"
    /// </summary>
    public string GetFormattedDisplayText()
    {
        string displayText = GetDisplayText();
        
        if (!string.IsNullOrEmpty(RelatedSkill))
        {
            return $"[{RelatedSkill}] {displayText}";
        }
        
        return displayText;
    }
    
    public ActionInfo(string actionText, string relatedSkill = "")
    {
        ActionText = actionText;
        RelatedSkill = relatedSkill;
    }
}
