using System.Collections.Generic;

namespace Cathedral.Game.Narrative;

/// <summary>
/// Tracks the current state of narration flow.
/// Manages history of narration blocks, current node, thinking attempts, etc.
/// </summary>
public class NarrationState
{
    public string CurrentNodeId { get; set; } = "";
    public int ThinkingAttemptsRemaining { get; set; } = 3;
    public string? SelectedKeyword { get; set; }
    public Skill? SelectedThinkingSkill { get; set; }
    public List<NarrationBlock> NarrationHistory { get; } = new();
    
    public void AddBlock(NarrationBlock block)
    {
        NarrationHistory.Add(block);
    }
    
    public void ClearHistory()
    {
        NarrationHistory.Clear();
    }
    
    public List<string> GetAllKeywords()
    {
        return NarrationHistory
            .Where(b => b.Keywords != null)
            .SelectMany(b => b.Keywords!)
            .Distinct()
            .ToList();
    }
}

/// <summary>
/// Represents a single block of narration text in the UI.
/// Can be observation, thinking (CoT), action result, or outcome.
/// </summary>
public record NarrationBlock(
    NarrationBlockType Type,                   // Observation, Thinking, Action, Outcome
    string SkillName,                          // Which skill generated this block
    string Text,                               // The narration text
    List<string>? Keywords,                    // Highlighted keywords (if observation)
    List<ParsedNarrativeAction>? Actions       // Clickable actions (if thinking)
);

/// <summary>
/// Types of narration blocks that can appear in the UI.
/// </summary>
public enum NarrationBlockType
{
    Observation,   // Skill perceives environment
    Thinking,      // Skill reasons about keyword (CoT)
    Action,        // Player selected action (skill check result)
    Outcome        // Result of action (success/failure)
}

/// <summary>
/// Represents an action generated by a thinking skill.
/// Extended version of ParsedAction for narrative system.
/// </summary>
public class ParsedNarrativeAction
{
    public string ActionText { get; set; } = "";              // Full text including "try to " prefix
    public string DisplayText { get; set; } = "";             // Text without "try to " prefix (for UI)
    public string ActionSkillId { get; set; } = "";           // Which action skill to use for check
    public Skill? ActionSkill { get; set; }                   // Resolved skill reference
    public Skill ThinkingSkill { get; set; } = null!;         // Which thinking skill generated this
    public Outcome PreselectedOutcome { get; set; } = null!;  // Success outcome chosen by thinking skill
    public string Keyword { get; set; } = "";                 // Keyword this action relates to
}
