using OpenTK.Mathematics;

namespace Cathedral.Game.Narrative;

/// <summary>
/// Melancholia humor — produced by the Spleen in response to specific narrative events
/// (trauma, curses, catastrophic failures). Unlike the four secretable humors, Melancholia
/// is never generated by normal organ secretion and has no associated secretion-percentage
/// derived stats. It is injected into the queue via <see cref="HumorQueue.Produce"/> by
/// gameplay event handlers.
///
/// Severely drains vital heat and imposes a -2 penalty on dice results.
/// </summary>
public sealed class MelancholiaHumor : BodyHumor
{
    public override string Name => "Melancholia";
    public override char Symbol => '\u263d'; // ☽
    public override Vector4 Color => new(0.50f, 0.50f, 0.50f, 1.0f);  // MediumGray50
    public override int VitalHeat => -2;
    public override TransmutingVirtue? TransmutingVirtue => new NumericModVirtue(-2);
}
